spring:
  profiles:
   active: stage

--- 
spring:
  profiles: stage
legacy.url:
current.url:
pilot.stores: 1144,1142


app:
  common:
    error:
      code: CB51101
    rest:
      connection-timeout: 10000
      read-timeout: 10000

modules:
  metrics:
    enabled: true
    metricReporterFormat: JSON
    endpointPath: metrics
    console:
      enabled: false
      flushInterval: 60000

management:
  port: 8080
  address: 127.0.0.1

---
spring:
  profiles: prod

app.key: ${RECEIVE_API_KEY}
blockaisle.url: https://api-internal.target.com/salesfloor_locations/v1?location_id=%s&floor=&block=&aisle=&key=${app.key}
blockaisle.legacy.url: http://t%sisp0001.target.com/ReplenishmentServices/api/BlockAisle/GetMasterBlockAisleDetails
pilot.stores: ${PILOT_STORES}

app:
  common:
    error:
      code: CB51101
    rest:
      connection-timeout: 10000
      read-timeout: 10000

modules:
  metrics:
    enabled: true
    metricReporterFormat: JSON
    endpointPath: metrics
    console:
      enabled: false
      flushInterval: 60000

management:
  port: 8080
  address: 127.0.0.1
